repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: double-quote-string-fixer
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/csachs/pyproject-flake8
    rev: v0.0.1a4
    hooks:
      - id: pyproject-flake8
        name: flake8
        description: 'A monkey patching wrapper to connect flake8 with pyproject.toml configuration'
        entry: pflake8
        language: python
        types: [ python ]
        require_serial: true
