# Generated by Django 4.1.2 on 2022-11-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='goalcategory',
            unique_together=set(),
        ),
    ]
