name: Build and deploy action
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/skypro_diplom:${{steps.tag.outputs.tag}}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/skypro_diplom:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/skypro_diplom:buildcache,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    env:
      ANSIBLE_VAULT_PASSWORD_FILE: /tmp/.vault_pass.txt
      VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true
      - name: Render template
        run: |
          echo "$VAULT_PASSWORD" > /tmp/.vault_pass.txt
          cat /tmp/.vault_pass.txt
          ansible-vault decrypt ./deploy/env
          ansible-vault decrypt ./deploy/docker-compose.yaml
          ansible-vault decrypt ./deploy/nginx/default.conf
          mv deploy/env deploy/.env
          printf "\nTAG_NAME=${{steps.tag.outputs.tag}}" >> deploy/.env
      - name: Copy on server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "deploy/*"
          target: diplom
          strip_components: 1

      - name: Run compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd diplom
            docker compose up -d

      - name: Clear after deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd diplom
            docker compose up -d
